# Generated by Django 4.2.4 on 2023-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_rename_client_mailinglist_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='last_send',
            field=models.DateTimeField(auto_now_add=True, verbose_name='последняя попытка'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('успешно', 'Success'), ('неудача', 'Fail')], max_length=10, verbose_name='статус попытки'),
        ),
    ]
