# Generated by Django 4.2.4 on 2023-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_alter_mailinglog_last_send_alter_mailinglog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mailing_list',
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='clients',
            field=models.ManyToManyField(to='mail_sender.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mailing_list',
            field=models.ManyToManyField(to='mail_sender.mailinglist', verbose_name='рассылка'),
        ),
    ]
