# Generated by Django 4.2.4 on 2023-08-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_remove_mail_mailing_list_alter_mailinglist_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mail_sender.client', verbose_name='клиент'),
        ),
    ]
