# Generated by Django 4.2.4 on 2023-08-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0005_mailinglog_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.client', verbose_name='клиент'),
        ),
    ]
